test-suites:
  awesome-app:
    command: bundle exec rspec --format json --out tmp/rspec.json --format documentation
    results:
      path: tmp/rspec.json
    partition:
      command: 'bundle exec rspec {{ testFiles }}'
      globs:
        - 'spec/**/*_spec.rb'
