test-suites:
  awesome-app:
    command: bundle exec rspec --format json --out tmp/rspec.json --format documentation
    results:
      path: tmp/rspec.json
    partition:
      command: 'bundle exec rspec {{ testFiles }}'
      globs:
        - 'spec/**/*_spec.rb'

  awesome-app-abq:
    command: bash -c "abq test --worker $ABQ_WORKER --run-id $CI_BUILD_ID --reporter rwx-v1-json=tmp/abq.json -- bundle exec rspec"
    results:
      path: tmp/abq.json
